/*
GLCP Unified API Routing Services API

Allow registration of information needed for routing GLCP APIs. 

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unifiedsdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppInstanceExtended type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppInstanceExtended{}

// AppInstanceExtended struct for AppInstanceExtended
type AppInstanceExtended struct {
	ApplicationInstanceId string `json:"applicationInstanceId"`
	Region string `json:"region"`
	ApplicationId string `json:"applicationId"`
	Id string `json:"id"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Type string `json:"type"`
	Generation *int32 `json:"generation,omitempty"`
	ExternalApiEndpoint *string `json:"externalApiEndpoint,omitempty"`
}

type _AppInstanceExtended AppInstanceExtended

// NewAppInstanceExtended instantiates a new AppInstanceExtended object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppInstanceExtended(applicationInstanceId string, region string, applicationId string, id string, type_ string) *AppInstanceExtended {
	this := AppInstanceExtended{}
	this.ApplicationInstanceId = applicationInstanceId
	this.Region = region
	this.ApplicationId = applicationId
	this.Id = id
	this.Type = type_
	return &this
}

// NewAppInstanceExtendedWithDefaults instantiates a new AppInstanceExtended object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppInstanceExtendedWithDefaults() *AppInstanceExtended {
	this := AppInstanceExtended{}
	return &this
}

// GetApplicationInstanceId returns the ApplicationInstanceId field value
func (o *AppInstanceExtended) GetApplicationInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationInstanceId
}

// GetApplicationInstanceIdOk returns a tuple with the ApplicationInstanceId field value
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetApplicationInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationInstanceId, true
}

// SetApplicationInstanceId sets field value
func (o *AppInstanceExtended) SetApplicationInstanceId(v string) {
	o.ApplicationInstanceId = v
}

// GetRegion returns the Region field value
func (o *AppInstanceExtended) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *AppInstanceExtended) SetRegion(v string) {
	o.Region = v
}

// GetApplicationId returns the ApplicationId field value
func (o *AppInstanceExtended) GetApplicationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetApplicationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *AppInstanceExtended) SetApplicationId(v string) {
	o.ApplicationId = v
}

// GetId returns the Id field value
func (o *AppInstanceExtended) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppInstanceExtended) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AppInstanceExtended) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AppInstanceExtended) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *AppInstanceExtended) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AppInstanceExtended) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AppInstanceExtended) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *AppInstanceExtended) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetType returns the Type field value
func (o *AppInstanceExtended) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppInstanceExtended) SetType(v string) {
	o.Type = v
}

// GetGeneration returns the Generation field value if set, zero value otherwise.
func (o *AppInstanceExtended) GetGeneration() int32 {
	if o == nil || IsNil(o.Generation) {
		var ret int32
		return ret
	}
	return *o.Generation
}

// GetGenerationOk returns a tuple with the Generation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetGenerationOk() (*int32, bool) {
	if o == nil || IsNil(o.Generation) {
		return nil, false
	}
	return o.Generation, true
}

// HasGeneration returns a boolean if a field has been set.
func (o *AppInstanceExtended) HasGeneration() bool {
	if o != nil && !IsNil(o.Generation) {
		return true
	}

	return false
}

// SetGeneration gets a reference to the given int32 and assigns it to the Generation field.
func (o *AppInstanceExtended) SetGeneration(v int32) {
	o.Generation = &v
}

// GetExternalApiEndpoint returns the ExternalApiEndpoint field value if set, zero value otherwise.
func (o *AppInstanceExtended) GetExternalApiEndpoint() string {
	if o == nil || IsNil(o.ExternalApiEndpoint) {
		var ret string
		return ret
	}
	return *o.ExternalApiEndpoint
}

// GetExternalApiEndpointOk returns a tuple with the ExternalApiEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppInstanceExtended) GetExternalApiEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalApiEndpoint) {
		return nil, false
	}
	return o.ExternalApiEndpoint, true
}

// HasExternalApiEndpoint returns a boolean if a field has been set.
func (o *AppInstanceExtended) HasExternalApiEndpoint() bool {
	if o != nil && !IsNil(o.ExternalApiEndpoint) {
		return true
	}

	return false
}

// SetExternalApiEndpoint gets a reference to the given string and assigns it to the ExternalApiEndpoint field.
func (o *AppInstanceExtended) SetExternalApiEndpoint(v string) {
	o.ExternalApiEndpoint = &v
}

func (o AppInstanceExtended) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppInstanceExtended) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applicationInstanceId"] = o.ApplicationInstanceId
	toSerialize["region"] = o.Region
	toSerialize["applicationId"] = o.ApplicationId
	toSerialize["id"] = o.Id
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Generation) {
		toSerialize["generation"] = o.Generation
	}
	if !IsNil(o.ExternalApiEndpoint) {
		toSerialize["externalApiEndpoint"] = o.ExternalApiEndpoint
	}
	return toSerialize, nil
}

func (o *AppInstanceExtended) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applicationInstanceId",
		"region",
		"applicationId",
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppInstanceExtended := _AppInstanceExtended{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppInstanceExtended)

	if err != nil {
		return err
	}

	*o = AppInstanceExtended(varAppInstanceExtended)

	return err
}

type NullableAppInstanceExtended struct {
	value *AppInstanceExtended
	isSet bool
}

func (v NullableAppInstanceExtended) Get() *AppInstanceExtended {
	return v.value
}

func (v *NullableAppInstanceExtended) Set(val *AppInstanceExtended) {
	v.value = val
	v.isSet = true
}

func (v NullableAppInstanceExtended) IsSet() bool {
	return v.isSet
}

func (v *NullableAppInstanceExtended) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppInstanceExtended(val *AppInstanceExtended) *NullableAppInstanceExtended {
	return &NullableAppInstanceExtended{value: val, isSet: true}
}

func (v NullableAppInstanceExtended) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppInstanceExtended) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


