/*
GLCP Unified API Routing Services API

Allow registration of information needed for routing GLCP APIs. 

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unifiedsdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomerProvisionExtended type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerProvisionExtended{}

// CustomerProvisionExtended struct for CustomerProvisionExtended
type CustomerProvisionExtended struct {
	ApplicationInstanceId string `json:"applicationInstanceId"`
	Region string `json:"region"`
	ApplicationId string `json:"applicationId"`
	WorkspaceId string `json:"workspaceId"`
	Id string `json:"id"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Type string `json:"type"`
	Generation *int32 `json:"generation,omitempty"`
}

type _CustomerProvisionExtended CustomerProvisionExtended

// NewCustomerProvisionExtended instantiates a new CustomerProvisionExtended object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerProvisionExtended(applicationInstanceId string, region string, applicationId string, workspaceId string, id string, type_ string) *CustomerProvisionExtended {
	this := CustomerProvisionExtended{}
	this.ApplicationInstanceId = applicationInstanceId
	this.Region = region
	this.ApplicationId = applicationId
	this.WorkspaceId = workspaceId
	this.Id = id
	this.Type = type_
	return &this
}

// NewCustomerProvisionExtendedWithDefaults instantiates a new CustomerProvisionExtended object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerProvisionExtendedWithDefaults() *CustomerProvisionExtended {
	this := CustomerProvisionExtended{}
	return &this
}

// GetApplicationInstanceId returns the ApplicationInstanceId field value
func (o *CustomerProvisionExtended) GetApplicationInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationInstanceId
}

// GetApplicationInstanceIdOk returns a tuple with the ApplicationInstanceId field value
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetApplicationInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationInstanceId, true
}

// SetApplicationInstanceId sets field value
func (o *CustomerProvisionExtended) SetApplicationInstanceId(v string) {
	o.ApplicationInstanceId = v
}

// GetRegion returns the Region field value
func (o *CustomerProvisionExtended) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *CustomerProvisionExtended) SetRegion(v string) {
	o.Region = v
}

// GetApplicationId returns the ApplicationId field value
func (o *CustomerProvisionExtended) GetApplicationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetApplicationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *CustomerProvisionExtended) SetApplicationId(v string) {
	o.ApplicationId = v
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *CustomerProvisionExtended) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *CustomerProvisionExtended) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetId returns the Id field value
func (o *CustomerProvisionExtended) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomerProvisionExtended) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CustomerProvisionExtended) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CustomerProvisionExtended) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *CustomerProvisionExtended) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *CustomerProvisionExtended) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CustomerProvisionExtended) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *CustomerProvisionExtended) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetType returns the Type field value
func (o *CustomerProvisionExtended) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CustomerProvisionExtended) SetType(v string) {
	o.Type = v
}

// GetGeneration returns the Generation field value if set, zero value otherwise.
func (o *CustomerProvisionExtended) GetGeneration() int32 {
	if o == nil || IsNil(o.Generation) {
		var ret int32
		return ret
	}
	return *o.Generation
}

// GetGenerationOk returns a tuple with the Generation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerProvisionExtended) GetGenerationOk() (*int32, bool) {
	if o == nil || IsNil(o.Generation) {
		return nil, false
	}
	return o.Generation, true
}

// HasGeneration returns a boolean if a field has been set.
func (o *CustomerProvisionExtended) HasGeneration() bool {
	if o != nil && !IsNil(o.Generation) {
		return true
	}

	return false
}

// SetGeneration gets a reference to the given int32 and assigns it to the Generation field.
func (o *CustomerProvisionExtended) SetGeneration(v int32) {
	o.Generation = &v
}

func (o CustomerProvisionExtended) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerProvisionExtended) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applicationInstanceId"] = o.ApplicationInstanceId
	toSerialize["region"] = o.Region
	toSerialize["applicationId"] = o.ApplicationId
	toSerialize["workspaceId"] = o.WorkspaceId
	toSerialize["id"] = o.Id
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Generation) {
		toSerialize["generation"] = o.Generation
	}
	return toSerialize, nil
}

func (o *CustomerProvisionExtended) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applicationInstanceId",
		"region",
		"applicationId",
		"workspaceId",
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerProvisionExtended := _CustomerProvisionExtended{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerProvisionExtended)

	if err != nil {
		return err
	}

	*o = CustomerProvisionExtended(varCustomerProvisionExtended)

	return err
}

type NullableCustomerProvisionExtended struct {
	value *CustomerProvisionExtended
	isSet bool
}

func (v NullableCustomerProvisionExtended) Get() *CustomerProvisionExtended {
	return v.value
}

func (v *NullableCustomerProvisionExtended) Set(val *CustomerProvisionExtended) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerProvisionExtended) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerProvisionExtended) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerProvisionExtended(val *CustomerProvisionExtended) *NullableCustomerProvisionExtended {
	return &NullableCustomerProvisionExtended{value: val, isSet: true}
}

func (v NullableCustomerProvisionExtended) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerProvisionExtended) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


