/*
GLCP Unified API Routing Services API

Allow registration of information needed for routing GLCP APIs. 

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unifiedsdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppInstanceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppInstanceList{}

// AppInstanceList struct for AppInstanceList
type AppInstanceList struct {
	Items []AppInstanceExtended `json:"items"`
	Count int32 `json:"count"`
	Next string `json:"next"`
}

type _AppInstanceList AppInstanceList

// NewAppInstanceList instantiates a new AppInstanceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppInstanceList(items []AppInstanceExtended, count int32, next string) *AppInstanceList {
	this := AppInstanceList{}
	this.Items = items
	this.Count = count
	this.Next = next
	return &this
}

// NewAppInstanceListWithDefaults instantiates a new AppInstanceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppInstanceListWithDefaults() *AppInstanceList {
	this := AppInstanceList{}
	return &this
}

// GetItems returns the Items field value
func (o *AppInstanceList) GetItems() []AppInstanceExtended {
	if o == nil {
		var ret []AppInstanceExtended
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AppInstanceList) GetItemsOk() ([]AppInstanceExtended, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AppInstanceList) SetItems(v []AppInstanceExtended) {
	o.Items = v
}

// GetCount returns the Count field value
func (o *AppInstanceList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *AppInstanceList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *AppInstanceList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value
func (o *AppInstanceList) GetNext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Next
}

// GetNextOk returns a tuple with the Next field value
// and a boolean to check if the value has been set.
func (o *AppInstanceList) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Next, true
}

// SetNext sets field value
func (o *AppInstanceList) SetNext(v string) {
	o.Next = v
}

func (o AppInstanceList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppInstanceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["count"] = o.Count
	toSerialize["next"] = o.Next
	return toSerialize, nil
}

func (o *AppInstanceList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"count",
		"next",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppInstanceList := _AppInstanceList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppInstanceList)

	if err != nil {
		return err
	}

	*o = AppInstanceList(varAppInstanceList)

	return err
}

type NullableAppInstanceList struct {
	value *AppInstanceList
	isSet bool
}

func (v NullableAppInstanceList) Get() *AppInstanceList {
	return v.value
}

func (v *NullableAppInstanceList) Set(val *AppInstanceList) {
	v.value = val
	v.isSet = true
}

func (v NullableAppInstanceList) IsSet() bool {
	return v.isSet
}

func (v *NullableAppInstanceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppInstanceList(val *AppInstanceList) *NullableAppInstanceList {
	return &NullableAppInstanceList{value: val, isSet: true}
}

func (v NullableAppInstanceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppInstanceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


