/*
GLCP Unified API Routing Services API

Allow registration of information needed for routing GLCP APIs. 

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unifiedsdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiGroupList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiGroupList{}

// ApiGroupList struct for ApiGroupList
type ApiGroupList struct {
	Items []ApiGroupExtended `json:"items"`
	Count int32 `json:"count"`
	Next string `json:"next"`
}

type _ApiGroupList ApiGroupList

// NewApiGroupList instantiates a new ApiGroupList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiGroupList(items []ApiGroupExtended, count int32, next string) *ApiGroupList {
	this := ApiGroupList{}
	this.Items = items
	this.Count = count
	this.Next = next
	return &this
}

// NewApiGroupListWithDefaults instantiates a new ApiGroupList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiGroupListWithDefaults() *ApiGroupList {
	this := ApiGroupList{}
	return &this
}

// GetItems returns the Items field value
func (o *ApiGroupList) GetItems() []ApiGroupExtended {
	if o == nil {
		var ret []ApiGroupExtended
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ApiGroupList) GetItemsOk() ([]ApiGroupExtended, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ApiGroupList) SetItems(v []ApiGroupExtended) {
	o.Items = v
}

// GetCount returns the Count field value
func (o *ApiGroupList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ApiGroupList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ApiGroupList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value
func (o *ApiGroupList) GetNext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Next
}

// GetNextOk returns a tuple with the Next field value
// and a boolean to check if the value has been set.
func (o *ApiGroupList) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Next, true
}

// SetNext sets field value
func (o *ApiGroupList) SetNext(v string) {
	o.Next = v
}

func (o ApiGroupList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiGroupList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["count"] = o.Count
	toSerialize["next"] = o.Next
	return toSerialize, nil
}

func (o *ApiGroupList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"count",
		"next",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiGroupList := _ApiGroupList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiGroupList)

	if err != nil {
		return err
	}

	*o = ApiGroupList(varApiGroupList)

	return err
}

type NullableApiGroupList struct {
	value *ApiGroupList
	isSet bool
}

func (v NullableApiGroupList) Get() *ApiGroupList {
	return v.value
}

func (v *NullableApiGroupList) Set(val *ApiGroupList) {
	v.value = val
	v.isSet = true
}

func (v NullableApiGroupList) IsSet() bool {
	return v.isSet
}

func (v *NullableApiGroupList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiGroupList(val *ApiGroupList) *NullableApiGroupList {
	return &NullableApiGroupList{value: val, isSet: true}
}

func (v NullableApiGroupList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiGroupList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


