/*
GLCP Unified API Routing Services API

Allow registration of information needed for routing GLCP APIs. 

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unifiedsdkgo

import (
	"encoding/json"
)

// checks if the AppInstancePatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppInstancePatch{}

// AppInstancePatch A JSONPatch document RFC 7396
type AppInstancePatch struct {
	ExternalApiEndpoint *string `json:"externalApiEndpoint,omitempty"`
}

// NewAppInstancePatch instantiates a new AppInstancePatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppInstancePatch() *AppInstancePatch {
	this := AppInstancePatch{}
	return &this
}

// NewAppInstancePatchWithDefaults instantiates a new AppInstancePatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppInstancePatchWithDefaults() *AppInstancePatch {
	this := AppInstancePatch{}
	return &this
}

// GetExternalApiEndpoint returns the ExternalApiEndpoint field value if set, zero value otherwise.
func (o *AppInstancePatch) GetExternalApiEndpoint() string {
	if o == nil || IsNil(o.ExternalApiEndpoint) {
		var ret string
		return ret
	}
	return *o.ExternalApiEndpoint
}

// GetExternalApiEndpointOk returns a tuple with the ExternalApiEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppInstancePatch) GetExternalApiEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalApiEndpoint) {
		return nil, false
	}
	return o.ExternalApiEndpoint, true
}

// HasExternalApiEndpoint returns a boolean if a field has been set.
func (o *AppInstancePatch) HasExternalApiEndpoint() bool {
	if o != nil && !IsNil(o.ExternalApiEndpoint) {
		return true
	}

	return false
}

// SetExternalApiEndpoint gets a reference to the given string and assigns it to the ExternalApiEndpoint field.
func (o *AppInstancePatch) SetExternalApiEndpoint(v string) {
	o.ExternalApiEndpoint = &v
}

func (o AppInstancePatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppInstancePatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalApiEndpoint) {
		toSerialize["externalApiEndpoint"] = o.ExternalApiEndpoint
	}
	return toSerialize, nil
}

type NullableAppInstancePatch struct {
	value *AppInstancePatch
	isSet bool
}

func (v NullableAppInstancePatch) Get() *AppInstancePatch {
	return v.value
}

func (v *NullableAppInstancePatch) Set(val *AppInstancePatch) {
	v.value = val
	v.isSet = true
}

func (v NullableAppInstancePatch) IsSet() bool {
	return v.isSet
}

func (v *NullableAppInstancePatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppInstancePatch(val *AppInstancePatch) *NullableAppInstancePatch {
	return &NullableAppInstancePatch{value: val, isSet: true}
}

func (v NullableAppInstancePatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppInstancePatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


